server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_restaurante
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true