server:
  port: 8080
  servlet:
    context-path: /restaurante/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_restaurante
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        show-sql: true
    open-in-view: true
  main:
    banner-mode: off
  jackson:
    time-zone: America/Sao_Paulo
  sql:
    init:
      mode: never
logging:
  file:
    name: logs/produtos.log
  level:
    com:
      restaurante:
        marmitas: DEBUG